apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-a2
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-a2
  template:
    metadata:
      labels:
        app: task-a2
    spec:
      containers:
      - name: task-a2-site
        image: taska2-frontend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: task-a2-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: task-a2
  ports:
  - port: 8080
    targetPort: 3000
